### ISSUE TITLE
Volunteer Arms is now The Cask & Still

### ISSUE THREAD

**Issue by dougalstanton** [skx/edinburgh.io#4]
I'm not sure how you're tracking name changes so I wasn't sure about this change. The pubs have their own file names so are you adding a new file for a new pub name, or just renaming the file and letting Git handle the history tracking?

Either way, pub's now got a new name and a total refit. See https://www.facebook.com/pages/The-Cask-Still/1478640755709335. No idea what it's like yet.

**Comment by skx** [comment]
Thanks for the update!

Renames aren't handled in a particularly clean way at the moment, and there is only one example:
- http://edinburgh.io/pubs/the-waterline.html
- http://edinburgh.io/pubs/the-leith-beer-co.html

The latter replacing the former.  The new pub links to the old name, but not vice-versa.  I should overhaul.  In fact I should go out and take more pictures and mull it over :)

**Comment by skx** [comment]
Renames are now handled, as per #5 :
- Old venues link to the current/new venue.
- All venues link to past names, if known.

TODO: Actually collect data for Cask & Still.  Will get that done ASAP.
